<!--
# Copyright 2021 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# This program may also be used under the terms of a commercial or
# enterprise edition license of COSMOS if purchased from the
# copyright holder
-->

<template>
  <v-dialog persistent v-model="show" width="500">
    <v-card>
      <v-system-bar>
        <v-spacer />
        <span> Imagery Provider Url </span>
        <v-spacer />
      </v-system-bar>

      <v-card-text>
        <v-row class="mt-3">
          Warning this is an advanced feature. Update or change the imagery
          provider Url for Cesium to use an imagery provider that provides tiled
          imagery as generated by MapTiler, GDAL2Tiles, etc.
        </v-row>
        <v-row>
          <v-text-field
            v-model="inputImageryProviderUrl"
            type="text"
            label="Imagery Provider Url"
            :rules="[rules.required]"
            :hint="url"
            data-test="input-imagery-provider-url"
          />
        </v-row>
        <v-row class="my-3">
          <span class="red--text" v-show="error" v-text="error" />
        </v-row>
        <v-row>
          <v-btn
            color="success"
            :disabled="!!error"
            @click="submit"
            data-test="imagery-provider-submit-btn"
          >
            Ok
          </v-btn>
          <v-spacer />
          <v-btn
            color="primary"
            @click="clear"
            data-test="imagery-provider-cancel-btn"
          >
            Cancel
          </v-btn>
        </v-row>
      </v-card-text>
    </v-card>
  </v-dialog>
</template>

<script>
import Api from '@cosmosc2/tool-common/src/services/api'

export default {
  props: {
    url: {
      type: String,
      required: true,
    },
    value: Boolean, // value is the default prop when using v-model
  },
  data() {
    return {
      rules: {
        required: (value) => !!value || 'Required',
      },
      inputImageryProviderUrl: '',
    }
  },
  computed: {
    error: function () {
      if (this.show === false) {
        return null
      }
      if (this.inputImageryProviderUrl === '') {
        return 'Url can not be blank.'
      }
      return null
    },
    show: {
      get() {
        return this.value
      },
      set(value) {
        this.$emit('input', value) // input is the default event when using v-model
      },
    },
  },
  methods: {
    clear: function () {
      this.show = !this.show
      this.inputImageryProviderUrl = ''
    },
    submit: function () {
      this.$emit('url', this.inputImageryProviderUrl)
      this.inputImageryProviderUrl = ''
      this.show = !this.show
    },
  },
}
</script>

<style scoped>
.theme--dark .v-card__title,
.theme--dark .v-card__subtitle {
  background-color: var(--v-secondary-darken3);
}
</style>
